# === Linux-specific configuration ===

# Shell: Fish
set-option -g default-shell /bin/sh
set-option -g default-command "exec /usr/bin/fish"

# Extra plugins: Session restore
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Status Bar - Theme Gruvbox Dark (transparent)
set -g status-bg default
set -g status-fg "#ebdbb2"
set -g status-style "bg=default,fg=#ebdbb2"
set -g status-position top
set -g status 2
set -g status-format[1] "#[fg=#504945]#(~/.config/tmux/tmux-border.sh)"
set -g status-justify left
set -g status-left-length 50
set -g status-right-length 100

set -g window-status-style "bg=default,fg=#7c6f64"
set -g window-status-current-style "bg=default,fg=#d79921"
set -g status-left-style "bg=default"
set -g status-right-style "bg=default"

set -g status-left "#{?#{@is-remote},#[fg=#d65d0e]󰢹 ,#[fg=#665c54]󰌢 }#[fg=#{?#{@is-remote},#d65d0e,#665c54}]#h #[fg=#7c6f64]󱂬 #{=25:session_name} │ "
set -g window-status-format "#[fg=#7c6f64]#I:#W "
set -g window-status-current-format "#[fg=#d79921]#I:#W "
set -g status-right "#[fg=#7c6f64]󰍛 #[fg=#d79921]#(~/.config/tmux/tmux-stats.sh cpu) #[fg=#7c6f64]󰢮 #[fg=#d79921]#(~/.config/tmux/tmux-stats.sh gpu) #[fg=#7c6f64]| 󰘚 #[fg=#d79921]#(~/.config/tmux/tmux-stats.sh ram)"

set -g pane-border-style "fg=#504945"
set -g pane-active-border-style "fg=#d79921"
set -g message-style "bg=default,fg=#d79921"
set -g mode-style "fg=#1d2021,bg=#d79921"
